
service: serverless-rest-api # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"

functions:
  create:
    handler: todos/create.create
    events: 
      - http:
          path: user
          method: post
          cors: true
  delete:
    handler: todos/delete.delete
    events: 
      - http:
          path: user/{id}
          method: delete
          cors: true
  getOne:
      handler: todos/getOne.getOne
      events: 
        - http:
            path: user/{id}
            method: get
            cors: true
  getAll:
      handler: todos/getAll.getAll
      events: 
        - http:
            path: user/
            method: get
            cors: true
  update:
      handler: todos/update.update
      events: 
        - http:
            path: user/{id}
            method: put
            cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'todos'