
service: mysql-api-serverless # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"

functions:
  
  # delete:
  #   handler: todos/delete.delete
  #   events: 
  #     - http:
  #         path: user/{id}
  #         method: delete
  #         cors: true
  
  # getAll:
  #     handler: todos/getAll.getAll
  #     events: 
  #       - http:
  #           path: user/
  #           method: get
  #           cors: true
  # update:
  #     handler: todos/update.update
  #     events: 
  #       - http:
  #           path: user/{id}
  #           method: put
  #           cors: true
  getData:
    handler: functions/getAll.getAll
    events:
      - http:
          path: db
          method: get
          cors: true
  getOne:
      handler: functions/getOne.getOne
      events: 
        - http:
            path: db/{id}
            method: get
            cors: true
  create:
    handler: functions/create.create
    events: 
      - http:
          path: db
          method: post
          cors: true